### ISSUE TITLE
New seabios version 1.3

### ISSUE THREAD

**Issue by ShFil119** [Thrilleratplay/coreboot-builder-scripts#13]
https://seabios.org/Releases#SeaBIOS_1.13.0

**Comment by Thrilleratplay** [comment]
@ShFil119   I do not understand what is being asked.  There was a SeaBIOS release but that does not have any bearing on this project.  These are only scripts to help automate building but the build specifics are left up to the end user.  If you are trying build with the latest SeaBIOS version, try building with the`--bleeding-edge` flag or configure SeaBIOS to build from master instead of stable.

**Comment by ShFil119** [comment]
You're right. Sorry.
